### ISSUE TITLE
Need your opinion on a case

### ISSUE THREAD

**Issue by fraxken** [MartinKolarik/is-minified-code#1]
Hi Martin,

I'm using your package on a security tool that i started few days ago (your package work very well). But i'v meet two cases where i would like to have your opinion:

https://github.com/tim-kos/node-retry/blob/master/index.js
and
https://github.com/browserify/resolve/tree/master/test (lot of cases here).

The following pattern is common:
```
module.exports = require("...");
// or
module.exports = "something";
```

That not a "BIG" problem.. but i wanted to get your feedback on these cases (and maybe look if you think there is room for improvment).

Best Regards,
Thomas

**Comment by MartinKolarik** [comment]
Hi, I'm aware of this, it popped up frequently during my testing. The behavior in this case changed between v1 and v2 of this module and IMHO both could be considered correct.

While a code like that was obviously written by hand and not minified, if you did try to minify it, you'd get the exact same thing (except whitespace around `=`), so you could say "it can't be minified further, so it's already minified". The reason I wrote this package was I needed to check if the code can be minified further (and if the minification is worth it) so I decided to go with this definition.

Also, there were some super small projects where the minified code was really just one line shorter than 200 chars.

**Comment by fraxken** [comment]
Hi,

Thanks for you feedback. I think this is not a big deal to consider these as "minified" codes too (as you explained they can't be minified more so it's seem correct). If you want to follow the project we work on: https://github.com/ES-Community/node-secure

I have an AST analysis too (so in these case i can check the number of nodes and exclude the minified if there is only one require statment).

Best Regards,
Thomas
